env:
  - distro: ubuntutrusty
    init: "/sbin/init"

services:
  - docker

script:
  - container_id=$(mktemp)
  - docker build -t container_under_test .
  - docker run --detach container_under_test "${init}" > "${container_id}"
  - docker exec "$(cat ${container_id})" env TERM=xterm ansible --version
  - docker exec "$(cat ${container_id})" env TERM=xterm ansible all -m ping

notifications:
  slack:
    secure: A8e+Z8A+XLFda0G1jYojq/31TlGqpc5MXiYfVTBNSej4aSOboG9sWySqMR5Qw8ruKboF7BRCthHwghfr54rsqqgr63pnemNLbMQN4pvt7J8BuGw3v7lgZRZj0UGUx3D+dMUggx4FE1lcZYDVv+ATkKH/wV75aQ5MqkceXQfJG0re801k8Jhak2/Qso0ge2xT5yx0megcWolf1iwoxByrfMPTq5Fag2nfcr+leltsyB5OPt0wmlhTfvdl11XwSw4eGkeTZqvtFoI7GzKXK5ACOi02sdCHwuSDYtnQi/GnvFF3TxabaQ2AvnVvk/87Lv1LL8SdYNJR6P/SdXgOOvRD5wbxOdO4JTC5yhfaAkjaDli3W02HBNpBILXWBnE3FuWO7fwaBBQKzc+0MEM2Fw5wCd9hQ6FfghtHh4rR6+rGzgQZArnu+Tpzg5O4xzGulesq7DoWuvAs0pMsQsfLBse+WvhYKWdCMnoQoINMx2Vb3SSC9iNaKhRsB4DHMxQCoqlgJFqYMejWTbFFd8xNQC7I7toAtD9ctsdiEcoXeWsiQX9QS4YddReDYT1zPh3GKYmhX7ZECy2A5K7Ex6nFk7ag0KkNC+jy5rTD51+N4urI5w1aoDM1dTk6MvdoeDaVAVcz7+fqmtMFE+l/hpo+K78uUFfzOhrG+xyPu4obupSj7nI=
